version: '3.3'

services:
  # ------------------------------------------------------------
  # Php
  # ------------------------------------------------------------
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
  # ------------------------------------------------------------
  # Nginx
  # ------------------------------------------------------------
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8910:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
